#!/command/with-contenv sh
while [ ! -f /var/run/avahi-daemon/pid ]; do
  echo "s6-rc: warning: avahi is not running, sleeping for 1 seconds before trying to start snapclient"
  sleep 1
done
echo "Starting snapclient"
exec /usr/local/bin/snapclient $ARG
